services:
  knownest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knownest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
